const COMMON_IPA_MAP: Record<string, string> = {
  the: 'ðə',
  a: 'ə',
  an: 'ən',
  and: 'ænd',
  is: 'ɪz',
  are: 'ɑːr',
  was: 'wɒz',
  were: 'wɜːr',
  to: 'tuː',
  in: 'ɪn',
  on: 'ɒn',
  at: 'æt',
  for: 'fɔːr',
  with: 'wɪð',
  this: 'ðɪs',
  that: 'ðæt',
  these: 'ðiːz',
  those: 'ðəʊz',
  you: 'juː',
  your: 'jɔːr',
  we: 'wiː',
  they: 'ðeɪ',
  he: 'hiː',
  she: 'ʃiː',
  it: 'ɪt',
  have: 'hæv',
  has: 'hæz',
  had: 'hæd',
  can: 'kæn',
  could: 'kʊd',
  will: 'wɪl',
  would: 'wʊd',
  should: 'ʃʊd',
  not: 'nɒt',
  be: 'biː',
  been: 'biːn',
  being: 'ˈbiː.ɪŋ',
  people: 'ˈpiː.pəl',
  world: 'wɜːld',
  time: 'taɪm',
  life: 'laɪf',
  work: 'wɜːk',
  great: 'ɡreɪt',
  important: 'ɪmˈpɔː.tənt',
  speaking: 'ˈspiː.kɪŋ',
  listening: 'ˈlɪs.ən.ɪŋ',
  reading: 'ˈriː.dɪŋ',
  writing: 'ˈraɪ.tɪŋ',
  learning: 'ˈlɜː.nɪŋ',
  technology: 'tekˈnɒl.ə.dʒi',
  future: 'ˈfjuː.tʃər',
  business: 'ˈbɪz.nɪs',
  education: 'ˌedʒ.ʊˈkeɪ.ʃən',
  modern: 'ˈmɒd.ən',
  dictionary: 'ˈdɪk.ʃən.ər.i',
  vocabulary: 'vəˈkæb.jə.lər.i',
  example: 'ɪɡˈzɑːm.pəl',
  pronunciation: 'prəˌnʌn.siˈeɪ.ʃən',
  schedule: 'ˈʃed.juːl',
  pedagogy: 'ˈped.ə.ɡɒdʒ.i',
  infrastructure: 'ˈɪn.frəˌstrʌk.tʃər',
  approximately: 'əˈprɒk.sɪ.mət.li',
  collaborative: 'kəˈlæb.ər.ə.tɪv',
  pivotal: 'ˈpɪv.ə.təl',
  indispensable: 'ˌɪn.dɪˈspen.sə.bəl',
  sustainability: 'səˌsteɪ.nəˈbɪl.ə.ti',
  environment: 'ɪnˈvaɪ.rən.mənt',
  system: 'ˈsɪs.təm',
  application: 'ˌæp.lɪˈkeɪ.ʃən',
  developer: 'dɪˈvel.ə.pər',
  practice: 'ˈpræk.tɪs',
  student: 'ˈstjuː.dənt',
  university: 'ˌjuː.nɪˈvɜː.sə.ti',
  communication: 'kəˌmjuː.nɪˈkeɪ.ʃən',
  language: 'ˈlæŋ.ɡwɪdʒ',
  english: 'ˈɪŋ.ɡlɪʃ',
  computer: 'kəmˈpjuː.tər',
  information: 'ˌɪn.fəˈmeɪ.ʃən',
  global: 'ˈɡləʊ.bəl',
  market: 'ˈmɑː.kɪt',
  company: 'ˈkʌm.pə.ni'
};

export function generateApproximateIPA(text: string): string {
  const words = text.trim().split(/\s+/);
  const ipaWords = words.map((w) => {
    const clean = w.toLowerCase().replace(/[^\w]/g, '');
    if (COMMON_IPA_MAP[clean]) {
      return COMMON_IPA_MAP[clean];
    }
    return clean;
  });
  return '/' + ipaWords.filter(Boolean).join(' ') + '/';
}
